import type { Bi } from './menu'

/** Visual descriptions of the photographs in the restaurant's printed menu. */
export const foodAlt: Record<string, Bi> = {
  'kitfo': { pl: 'Kitfo z białym serem i zieleniną na talerzu z injerą.', en: 'Kitfo with white cheese and greens on a plate with injera.' },
  'doro-wot': { pl: 'Doro Wot z jajkiem w czerwonym sosie, podane z injerą.', en: 'Doro Wot with an egg in a red sauce, served with injera.' },
  'siga-firfir': { pl: 'Siga Firfir z kawałkami injery i zieloną papryczką.', en: 'Siga Firfir with pieces of injera and a green pepper.' },
  'doro-tibs': { pl: 'Kawałki kurczaka Doro Tibs na talerzu wyłożonym injerą.', en: 'Doro Tibs chicken pieces on an injera-lined plate.' },
  'dekak-tibs': { pl: 'Dekak Tibs w czarnym naczyniu, obok rulonu injery.', en: 'Dekak Tibs in a black dish beside a roll of injera.' },
  'dulet': { pl: 'Dulet z posiekaną zieleniną w czarnym naczyniu.', en: 'Dulet topped with chopped greens in a black dish.' },
  'yeawaze-tibs': { pl: 'Yeawaze Tibs z zielonymi papryczkami i injerą.', en: 'Yeawaze Tibs with green peppers and injera.' },
  'merek-tibs': { pl: 'Merek Tibs z kawałkami czerwonej i zielonej papryki.', en: 'Merek Tibs with pieces of red and green pepper.' },
  'shekla-tibs': { pl: 'Shekla Tibs w podgrzewanym naczyniu, z papryczkami i rozmarynem.', en: 'Shekla Tibs in a heated serving dish with peppers and rosemary.' },
  'key-wot': { pl: 'Czerwony gulasz Key Wot z rulonem injery.', en: 'Red Key Wot stew with a roll of injera.' },
  'dinch-be-siga': { pl: 'Dinch be Siga: gulasz z kawałkami mięsa i ziemniaków.', en: 'Dinch be Siga: stew with pieces of meat and potato.' },
  'bozena-shiro': { pl: 'Bozena Shiro w podłużnym naczyniu, obok sałatki i injery.', en: 'Bozena Shiro in an oval dish beside salad and injera.' },
  'half-half': { pl: 'Half Half: dwa dania podane obok siebie.', en: 'Half Half: two dishes served side by side.' },
  'misir-wot': { pl: 'Misir Wot w miseczce na talerzu z injerą.', en: 'Misir Wot in a bowl on a plate with injera.' },
  'kik-wot': { pl: 'Żółty Kik Wot z zieloną papryczką i injerą.', en: 'Yellow Kik Wot with a green pepper and injera.' },
  'gomen-be-dinch': { pl: 'Gomen be Dinch: zielenina i ziemniaki podane z injerą.', en: 'Gomen be Dinch: greens and potatoes served with injera.' },
  'keysir': { pl: 'Keysir: czerwone buraki i ziemniaki na wzorzystym talerzu.', en: 'Keysir: red beetroot and potatoes on a patterned plate.' },
  'tikil-gomen': { pl: 'Tikil Gomen: żółta kapusta z marchewką, obok injery.', en: 'Tikil Gomen: yellow cabbage and carrots beside injera.' },
  'fosolia': { pl: 'Fasolka i marchewka Fosolia na talerzu z injerą.', en: 'Fosolia green beans and carrots on a plate with injera.' },
  'shiro': { pl: 'Shiro w czarnym dzbanku, obok sałatki i injery.', en: 'Shiro in a black pot beside salad and injera.' },
  'alicha-dinich': { pl: 'Alicha Dinich: żółte ziemniaki z marchewką.', en: 'Alicha Dinich: yellow potatoes with carrots.' },
  'firfir': { pl: 'Firfir na injerze, z plastrami pomidora i papryczką.', en: 'Firfir on injera with sliced tomato and a pepper.' },
  'suf-fitfit': { pl: 'Rulony injery Suf Fitfit z pomidorem i zielonymi papryczkami.', en: 'Suf Fitfit injera rolls with tomato and green peppers.' },
  'pasta': { pl: 'Spaghetti z czerwonym sosem i zieleniną.', en: 'Spaghetti with red sauce and greens.' },
  'salad': { pl: 'Zielona sałata z pomidorem i posiekaną cebulą.', en: 'Green lettuce with tomato and chopped onion.' },
  'timatim-kurt': { pl: 'Timatim Kurt: pokrojone pomidory z cebulą i zielonymi papryczkami.', en: 'Timatim Kurt: chopped tomatoes with onion and green peppers.' },
  'veggie-rice': { pl: 'Żółty ryż z warzywami na wzorzystym talerzu.', en: 'Yellow vegetable rice on a patterned plate.' },
  'karya-sineg': { pl: 'Zielone papryczki Karya Sineg wypełnione warzywami.', en: 'Green Karya Sineg peppers filled with vegetables.' },
  'plain-rice': { pl: 'Porcja białego ryżu na talerzu.', en: 'A serving of white rice on a plate.' },
  'meat-combo': { pl: 'Talerz do dzielenia z daniami mięsnymi, warzywami i rulonami injery.', en: 'A sharing platter with meat dishes, vegetables and injera rolls.' },
  'vegan-combo': { pl: 'Talerz wegański z kolorowymi daniami i rulonami injery.', en: 'A vegan platter with colourful dishes and injera rolls.' },
  'basket': { pl: 'Dania podane w tradycyjnym plecionym koszu z pokrywą.', en: 'Food served in a traditional woven basket with a lid.' },
  'tej': { pl: 'Złocisty tej w szklanej karafce z wąską szyjką.', en: 'Golden tej in a narrow-necked glass carafe.' },
  'coffee': { pl: 'Kawa nalewana z dzbanka jebena do małej filiżanki.', en: 'Coffee poured from a jebena pot into a small cup.' },
}
